@startuml Uber Checkout
participant LoB_Mobile
participant Checkout_Mobile
participant LoB_Backend
participant Checkout_Backend

activate LoB_Mobile
LoB_Mobile -> Checkout_Mobile : Run pre-checkout actions
activate Checkout_Mobile
Checkout_Mobile -> Checkout_Mobile : Run actions
Checkout_Mobile --> LoB_Mobile : Checkout actions results

LoB_Mobile -> LoB_Backend : Place Order (Action Results)
activate LoB_Backend
LoB_Backend -> Checkout_Backend : Prepare Checkout (Action Results)
activate Checkout_Backend
Checkout_Backend --> LoB_Backend : Failure, new Checkout Actions
deactivate Checkout_Backend
LoB_Backend --> LoB_Mobile : Failure, Checkout Actions
deactivate LoB_Backend

LoB_Mobile -> Checkout_Mobile : Run post-checkout actions
Checkout_Mobile -> Checkout_Mobile : Run actions
Checkout_Mobile --> LoB_Mobile : Checkout actions results
deactivate Checkout_Mobile

LoB_Mobile -> LoB_Backend : Place Order (Action Results)
activate LoB_Backend
LoB_Backend -> Checkout_Backend : Prepare Checkout (Action Results)
activate Checkout_Backend
Checkout_Backend --> LoB_Backend : Success
deactivate Checkout_Backend
LoB_Backend --> LoB_Mobile : Success, order status
deactivate LoB_Backend
deactivate LoB_Mobile
@enduml